apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
spec:
  serviceName: opensearch
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: OPENSEARCH_PASS
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - 'curl -fsS http://localhost:9200/_cluster/health | grep -qv ''"status":"red"'''
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'curl -fsS http://localhost:9200/_cluster/health | grep -qv ''"status":"red"'''
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
