apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ro-dou.fullname" . }}-airflow-secrets
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: airflow
type: Opaque
stringData:
{{- range $key, $value := .Values.airflow.secrets }}
{{- if ne $key "AIRFLOW__SMTP__SMTP_HOST" }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
  AIRFLOW__SMTP__SMTP_HOST: {{ default (printf "%s-smtp4dev" (include "ro-dou.fullname" .)) .Values.airflow.secrets.AIRFLOW__SMTP__SMTP_HOST | quote }}
  AIRFLOW_CONN_INLABS_DB: {{ printf "postgres://%s:%s@%s-postgres/inlabs" (index .Values.postgres.secrets "postgres-user") (index .Values.postgres.secrets "postgres-password") (include "ro-dou.fullname" .) | quote }}
