apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ro-dou.fullname" . }}-airflow-logs-pvc
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: airflow
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.airflow.pvc.storageClassName }}
  storageClassName: {{ .Values.airflow.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.airflow.pvc.storage }}