apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ro-dou.fullname" . }}-airflow-secrets
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: airflow
type: Opaque
stringData:
{{- range $key, $value := .Values.airflow.secrets }}
{{- if ne $key "AIRFLOW__SMTP__SMTP_HOST" }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
  AIRFLOW__SMTP__SMTP_HOST: {{ default (printf "%s-smtp4dev" (include "ro-dou.fullname" .)) .Values.airflow.secrets.AIRFLOW__SMTP__SMTP_HOST | quote }}
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: {{ printf "postgresql+psycopg2://%s:%s@%s-postgres/%s" (index .Values.postgres.secrets "postgres-user") (index .Values.postgres.secrets "postgres-password") (include "ro-dou.fullname" .) (index .Values.postgres.secrets "postgres-db") | quote }}
  AIRFLOW_CONN_EXAMPLE_DATABASE_CONN: {{ printf "postgresql://%s:%s@%s-postgres:%v/%s" (index .Values.postgres.secrets "postgres-user") (index .Values.postgres.secrets "postgres-password") (include "ro-dou.fullname" .) .Values.postgres.service.port (index .Values.postgres.secrets "postgres-db") | quote }}
  AIRFLOW_CONN_INLABS_DB: {{ printf "postgres://%s:%s@%s-postgres/inlabs" (index .Values.postgres.secrets "postgres-user") (index .Values.postgres.secrets "postgres-password") (include "ro-dou.fullname" .) | quote }}
{{- $smtpExtra := dict "disable_ssl" true "from_email" (index .Values.airflow.secrets "AIRFLOW__SMTP__SMTP_MAIL_FROM") }}
{{- if ne (index .Values.airflow.secrets "AIRFLOW__SMTP__SMTP_STARTTLS" | lower) "true" }}
{{- $_ := set $smtpExtra "disable_tls" true }}
{{- end }}
  AIRFLOW_CONN_SMTP_DEFAULT: {{ printf "smtp://%s:%s@%s:%v?__extra__=%s" (index .Values.airflow.secrets "AIRFLOW__SMTP__SMTP_USER" | urlquery) (index .Values.airflow.secrets "AIRFLOW__SMTP__SMTP_PASSWORD" | urlquery) (default (printf "%s-smtp4dev" (include "ro-dou.fullname" .)) .Values.airflow.secrets.AIRFLOW__SMTP__SMTP_HOST) (index .Values.airflow.secrets "AIRFLOW__SMTP__SMTP_PORT") ($smtpExtra | toJson | urlquery) | quote }}
