apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ro-dou.fullname" . }}-airflow-dag-processor
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: airflow-dag-processor
spec:
  replicas: {{ .Values.airflow.dagProcessor.replicas }}
  selector:
    matchLabels:
      app: airflow-dag-processor
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: airflow-dag-processor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: airflow-dag-processor
          image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          command: ["airflow", "dag-processor"]
          envFrom:
            - secretRef:
                name: {{ include "ro-dou.fullname" . }}-airflow-secrets
            - configMapRef:
                name: {{ include "ro-dou.fullname" . }}-airflow-config
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: {{ include "ro-dou.fullname" . }}-airflow-logs-pvc
