apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ro-dou.fullname" . }}-airflow-create-variables-job
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: airflow
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: airflow-create-variables-job
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
      - name: create-variables
        image: {{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}
        imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
        command: ["bash", "-c"]
        args:
          - |
            {{- include "ro-dou.waitForPostgres" . | nindent 12 }}
            cat <<'EOF' > /tmp/variables.json
            {
              "path_tmp": "/tmp",
              "email_admin": "admin@rodou.gov.br",
              "termos_exemplo_variavel": "LGPD\nlei geral de proteção de dados\nacesso à informação",
              "RO_DOU_INLABS_USE_OPENSEARCH": {{ ternary "True" "False" .Values.opensearch.connection.enabled | quote }},
              "OPENSEARCH_HOST": {{ default (printf "http://%s-opensearch:%v" (include "ro-dou.fullname" .) .Values.opensearch.service.port) .Values.opensearch.connection.host | quote }}
            }
            EOF
            airflow variables import /tmp/variables.json
            airflow variables set OPENSEARCH_USER "$OPENSEARCH_USER"
            airflow variables set OPENSEARCH_PASS "$OPENSEARCH_PASS"
        envFrom:
          - secretRef:
              name: {{ include "ro-dou.fullname" . }}-airflow-secrets
          - configMapRef:
              name: {{ include "ro-dou.fullname" . }}-airflow-config
  backoffLimit: 0
