apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ro-dou.fullname" . }}-airflow-secrets
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: airflow
type: Opaque
stringData:
{{- range $key, $value := .Values.airflow.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}