apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ro-dou.fullname" . }}-postgres-secret
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: postgres
type: Opaque
stringData:
{{- range $key, $value := .Values.postgres.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}