apiVersion: v1
kind: Service
metadata:
  name: {{ include "ro-dou.fullname" . }}-postgres
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: postgres
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      name: postgres
  selector:
    app: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ro-dou.fullname" . }}-postgres
  labels:
    {{- include "ro-dou.labels" . | nindent 4 }}
    app: postgres
spec:
  serviceName: "{{ include "ro-dou.fullname" . }}-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ index .Values.postgres.secrets "postgres-db" }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "ro-dou.fullname" . }}-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ro-dou.fullname" . }}-postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        labels:
          app: postgres
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}