# Default values for ro-dou chart

# Airflow configuration
airflow:
  image:
    repository: ghcr.io/gestaogovbr/ro-dou
    tag: latest
    pullPolicy: IfNotPresent
  apiServer:
    replicas: 1
    port: 8080
  scheduler:
    replicas: 1
  dagProcessor:
    replicas: 1
  config:
    AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Sao_Paulo"
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
    AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    AIRFLOW__CORE__FERNET_KEY: "Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw="
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE: "false"
    AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY: "false"
    AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "America/Sao_Paulo"
    AIRFLOW__WEBSERVER__SECRET_KEY: "42"
    AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
    AIRFLOW__API_AUTH__JWT_SECRET: "42"
    _AIRFLOW_DB_MIGRATE: "true"
    RO_DOU__DAG_CONF_DIR: "/opt/airflow/dags/ro_dou/dag_confs"
    AIRFLOW_VAR_PATH_TMP: "/tmp"
  secrets:
    AIRFLOW__SMTP__SMTP_HOST: "smtp4dev"
    AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@email.gov.br"
    AIRFLOW__SMTP__SMTP_PORT: "25"
    AIRFLOW__SMTP__SMTP_STARTTLS: "false"
    AIRFLOW__SMTP__SMTP_USER: ""
    AIRFLOW__SMTP__SMTP_PASSWORD: ""
    INLABS_PORTAL_LOGIN: ""
    INLABS_PORTAL_PASSWORD: ""
  pvc:
    storage: 1Gi
    storageClassName: "nfs-seges"

# PostgreSQL configuration
postgres:
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  secrets:
    postgres-user: "airflow"
    postgres-password: "airflow"
    postgres-db: "airflow"
  storage: 5Gi

# SMTP4Dev configuration
smtp4dev:
  image:
    repository: rnwood/smtp4dev
    tag: v3
    pullPolicy: IfNotPresent
  service:
    webPort: 5001
    smtpPort: 25
    imapPort: 143