FROM node:22-alpine

WORKDIR /app/mcp/frontend

COPY mcp/frontend/package.json /app/mcp/frontend/package.json
RUN npm install

COPY mcp/frontend /app/mcp/frontend

EXPOSE 5173

CMD ["npm", "run", "dev"]
