apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
        - name: smtp4dev
          image: rnwood/smtp4dev:v3
          ports:
            - containerPort: 80   # Web UI
            - containerPort: 25   # SMTP
            - containerPort: 143  # IMAP
          env:
            - name: ServerOptions__HostName
              value: smtp4dev
---
apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
spec:
  type: ClusterIP
  selector:
    app: smtp4dev
  ports:
    - name: web
      port: 5001
      targetPort: 80
    - name: smtp
      port: 25
      targetPort: 25
    - name: imap
      port: 143
      targetPort: 143