apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-api-server
spec:
  template:
    spec:
      containers:
        - name: airflow-api-server
          volumeMounts:
            - name: dag-confs
              mountPath: /opt/airflow/dags/ro_dou/dag_confs
              readOnly: true
      volumes:
        - name: dag-confs
          persistentVolumeClaim:
            claimName: dag-confs-pvc
