from enum import Enum
from datetime import datetime, timedelta

class Section(Enum):
    """Define the section options to be used as parameter in the search"""

    SECAO_1 = "do1"
    SECAO_2 = "do2"
    SECAO_3 = "do3"
    EDICAO_EXTRA = "doe"
    EDICAO_EXTRA_1A = "do1_extra_a"
    EDICAO_EXTRA_1B = "do1_extra_b"
    EDICAO_EXTRA_1D = "do1_extra_d"
    EDICAO_EXTRA_2A = "do2_extra_a"
    EDICAO_EXTRA_2B = "do2_extra_b"
    EDICAO_EXTRA_2D = "do2_extra_d"
    EDICAO_EXTRA_3A = "do3_extra_a"
    EDICAO_EXTRA_3B = "do3_extra_b"
    EDICAO_EXTRA_3D = "do3_extra_d"
    EDICAO_SUPLEMENTAR = "do1a"
    TODOS = "todos"

class SectionINLABS(Enum):
    """Define the section options to be used as parameter in the search"""

    SECAO_1 = "DO1"
    SECAO_2 = "DO2"
    SECAO_3 = "DO3"
    EDICAO_EXTRA = "DO1E"
    EDICAO_EXTRA_1 = "DO1E"
    EDICAO_EXTRA_2 = "DO2E"
    EDICAO_EXTRA_3 = "DO3E"
    EDICAO_EXTRA_1A = "DO1E"
    EDICAO_EXTRA_1B = "DO1E"
    EDICAO_EXTRA_1D = "DO1E"
    EDICAO_EXTRA_2A = "DO2E"
    EDICAO_EXTRA_2B = "DO2E"
    EDICAO_EXTRA_2D = "DO2E"
    EDICAO_EXTRA_3A = "DO3E"
    EDICAO_EXTRA_3B = "DO3E"
    EDICAO_EXTRA_3D = "DO3E"
    EDICAO_SUPLEMENTAR = "DO1E"

class SearchDate(Enum):
    """Define the search date options to be used as parameter in the search"""

    DIA = "dia"
    SEMANA = "semana"
    MES = "mes"
    ANO = "ano"


class Field(Enum):
    """Define the search field options to be used as parameter in the search"""

    TUDO = "tudo"
    TITULO = "title_pt_BR"
    CONTEUDO = "ddm__text__21040__texto_pt_BR"

class Pubtype(Enum):
    """Define the publication type options to be used as parameter in the search"""

    ACAO_DIRETA_DE_INCONSTITUCIONALIDADE_E_ACAO_DECLARATORIA_DE_CONSTITUCIONALIDADE = "Ação direta de inconstitucionalidade e ação declaratória de constitucionalidade"
    ACORDAO = "Acórdão"
    ACORDO_COLETIVO_DE_TRABALHO = "Acordo coletivo de trabalho"
    AJUSTE = "Ajuste"
    ALVARA = "Alvará"
    ARESTO = "Aresto"
    ATA = "Ata"
    ATO = "Ato"
    ATO_COMPLEMENTAR = "Ato complementar"
    ATO_CONCESSORIO = "Ato concessório"
    ATO_DECLARATORIO = "Ato declaratório"
    ATO_DECLARATORIO_CONJUNTO = "Ato declaratório conjunto"
    ATO_NORMATIVO = "Ato normativo"
    ATO_REGIMENTAL = "Ato regimental"
    ATO_REGULAMENTAR = "Ato regulamentar"
    AUTO_DE_INFRACAO = "Auto de infração"
    AUTORIZACAO = "Autorização"
    AVISO = "Aviso"
    AVISO_AOS_ACIONISTAS = "Aviso aos acionistas"
    AVISO_DE_ADIAMENTO = "Aviso de adiamento"
    AVISO_DE_ADJUDICACAO = "Aviso de adjudicação"
    AVISO_DE_ALIENACAO = "Aviso de alienação"
    AVISO_DE_ALTERACAO = "Aviso de alteração"
    AVISO_DE_ALTERACAO_DE_RESULTADO_DE_HABILITACAO = "Aviso de alteração de resultado de habilitação"
    AVISO_DE_ANULACAO = "Aviso de anulação"
    AVISO_DE_AUDIENCIA_PUBLICA = "Aviso de audiência pública"
    AVISO_DE_CADASTRAMENTO = "Aviso de cadastramento"
    AVISO_DE_CANCELAMENTO = "Aviso de cancelamento"
    AVISO_DE_CANCELAMENTO_DE_TERMO_ADITIVO = "Aviso de cancelamento de termo aditivo"
    AVISO_DE_CHAMAMENTO_PUBLICO = "Aviso de chamamento público"
    AVISO_DE_COLETA_DE_PRECOS = "Aviso de coleta de preços"
    AVISO_DE_CONSULTA_PUBLICA = "Aviso de consulta pública"
    AVISO_DE_CONVALIDACAO = "Aviso de convalidação"
    AVISO_DE_CREDENCIAMENTO = "Aviso de credenciamento"
    AVISO_DE_DISPENSA_DE_LICITACAO = "Aviso de dispensa de licitação"
    AVISO_DE_ELEICAO = "Aviso de eleição"
    AVISO_DE_EXTRAVIO = "Aviso de extravio"
    AVISO_DE_FATO_RELEVANTE = "Aviso de fato relevante"
    AVISO_DE_HABILITACAO = "Aviso de habilitação"
    AVISO_DE_HOMOLOGACAO = "Aviso de homologação"
    AVISO_DE_HOMOLOGACAO_E_ADJUDICACAO = "Aviso de homologação e adjudicação"
    AVISO_DE_INDICE_TECNICO = "Aviso de índice técnico"
    AVISO_DE_INEXIGIBILIDADE_DE_LICITACAO = "Aviso de inexigibilidade de licitação"
    AVISO_DE_JULGAMENTO = "Aviso de julgamento"
    AVISO_DE_LICENCA = "Aviso de licença"
    AVISO_DE_LICITACAO = "Aviso de licitação"
    AVISO_DE_LICITACAO_CONCORRENCIA = "Aviso de licitação-concorrência"
    AVISO_DE_LICITACAO_CONVITE = "Aviso de licitação-convite"
    AVISO_DE_LICITACAO_DESERTA = "Aviso de licitação deserta"
    AVISO_DE_LICITACAO_LEILAO = "Aviso de licitação-leilão"
    AVISO_DE_LICITACAO_PREGAO = "Aviso de licitação-pregão"
    AVISO_DE_LICITACAO_RDC_ELETRONICO = "Aviso de licitação-rdc eletrônico"
    AVISO_DE_LICITACAO_RDC_PRESENCIAL = "Aviso de licitação-rdc presencial"
    AVISO_DE_LICITACAO_REGISTRO_DE_PRECOS = "Aviso de licitação-registro de preços"
    AVISO_DE_LICITACAO_TOMADA_DE_PRECOS = "Aviso de licitação-tomada de preços"
    AVISO_DE_NOTA_TECNICA = "Aviso de nota técnica"
    AVISO_DE_PADRONIZACAO = "Aviso de padronização"
    AVISO_DE_PENALIDADE = "Aviso de penalidade"
    AVISO_DE_PRECOS_REGISTRADOS = "Aviso de preços registrados"
    AVISO_DE_PRE_QUALIFICACAO = "Aviso de pré-qualificação"
    AVISO_DE_PROCESSO_SELETIVO = "Aviso de processo seletivo"
    AVISO_DE_PROPOSTA_COMERCIAL = "Aviso de proposta comercial"
    AVISO_DE_PROPOSTA_TECNICA = "Aviso de proposta técnica"
    AVISO_DE_PRORROGACAO = "Aviso de prorrogação"
    AVISO_DE_REABERTURA_DE_PRAZO = "Aviso de reabertura de prazo"
    AVISO_DE_REGISTRO_DE_CHAPAS = "Aviso de registro de chapas"
    AVISO_DE_REGISTRO_DE_DIPLOMAS = "Aviso de registro de diplomas"
    AVISO_DE_REGISTRO_DE_PRECOS = "Aviso de registro de preços"
    AVISO_DE_RELACAO_DE_COMPRAS = "Aviso de relação de compras"
    AVISO_DE_RESCISAO = "Aviso de rescisão"
    AVISO_DE_RETIFICACAO = "Aviso de retificação"
    AVISO_DE_REVOGACAO = "Aviso de revogação"
    AVISO_DE_SELECAO = "Aviso de seleção"
    AVISO_DE_SERVICO_E_COMPRA = "Aviso de serviço e compra"
    AVISO_DE_SORTEIO = "Aviso de sorteio"
    AVISO_DE_SUSPENSAO = "Aviso de suspensão"
    AVISO_DE_TOMADA_DE_SUBSIDIOS = "Aviso de tomada de subsídios"
    BALANCETE = "Balancete"
    BALANCETE_FINANCEIRO = "Balancete financeiro"
    BALANCETE_PATRIMONIAL_E_FINANCEIRO = "Balancete patrimonial e financeiro"
    BALANCO_PATRIMONIAL = "Balanço patrimonial"
    BALANCO_SOCIAL = "Balanço social"
    CERTIDAO = "Certidão"
    CIRCULAR = "Circular"
    COMUNICADO = "Comunicado"
    CONSULTA_PUBLICA = "Consulta pública"
    CONTRATO_DE_GESTAO = "Contrato de gestão"
    CONVENIO = "Convênio"
    DECISAO = "Decisão"
    DECRETO = "Decreto"
    DECRETO_DE_PESSOAL = "Decreto de pessoal"
    DECRETO_LEGISLATIVO = "Decreto legislativo"
    DECRETO_NAO_NUMERADO = "Decreto não numerado"
    DECRETO_NUMERADO = "Decreto numerado"
    DELIBERACAO = "Deliberação"
    DEMONSTRACAO_CONTABIL = "Demonstração contábil"
    DESPACHO = "Despacho"
    DESPACHO_INTERMINISTERIAL = "Despacho interministerial"
    EDITAL = "Edital"
    EDITAL_DA_JUSTICA_GRATUITA = "Edital da justiça gratuita (art. 32 portaria 268/2009-in)"
    EDITAL_DE_CITACAO = "Edital de citação"
    EDITAL_DE_CONCURSO_PUBLICO = "Edital de concurso público"
    EDITAL_DE_CONVOCACAO = "Edital de convocação"
    EDITAL_DE_CREDENCIAMENTO = "Edital de credenciamento"
    EDITAL_DE_INTIMACAO = "Edital de intimação"
    EDITAL_DE_LEILAO = "Edital de leilão"
    EDITAL_DE_NOTIFICACAO = "Edital de notificação"
    EDITAL_DE_PROCESSO_SELETIVO = "Edital de processo seletivo"
    EDITAL_DE_VESTIBULAR = "Edital de vestibular"
    EMENDA = "Emenda"
    EMENDA_CONSTITUCIONAL = "Emenda constitucional"
    ESTATUTO = "Estatuto"
    EXTRATO = "Extrato"
    EXTRATO_DA_ATA = "Extrato da ata"
    EXTRATO_DE_ACORDO_DE_COOPERACAO = "Extrato de acordo de cooperação"
    EXTRATO_DE_ACORDO_DE_COOPERACAO_FEDERATIVA = "Extrato de acordo de cooperação federativa"
    EXTRATO_DE_ACORDO_DE_COOPERACAO_TECNICA = "Extrato de acordo de cooperação técnica"
    EXTRATO_DE_ADESAO = "Extrato de adesão"
    EXTRATO_DE_AJUSTE = "Extrato de ajuste"
    EXTRATO_DE_APOSTILAMENTO = "Extrato de apostilamento"
    EXTRATO_DE_AUTORIZACAO_DE_FORNECIMENTO_DE_MATERIAL = "Extrato de autorização de fornecimento de material"
    EXTRATO_DE_AUTORIZACAO_DE_SERVICO = "Extrato de autorização de serviço"
    EXTRATO_DE_AUTORIZACAO_DE_USO = "Extrato de autorização de uso"
    EXTRATO_DE_CARTA_CONTRATO = "Extrato de carta contrato"
    EXTRATO_DE_CARTA_REVERSAL = "Extrato de carta reversal"
    EXTRATO_DE_CESSAO = "Extrato de cessão"
    EXTRATO_DE_CESSAO_DE_USO = "Extrato de cessão de uso"
    EXTRATO_DE_COMODATO = "Extrato de comodato"
    EXTRATO_DE_COMPROMISSO = "Extrato de compromisso"
    EXTRATO_DE_CONCESSAO_DE_USO = "Extrato de concessão de uso"
    EXTRATO_DE_CONTRATO = "Extrato de contrato"
    EXTRATO_DE_CONVENIO = "Extrato de convênio"
    EXTRATO_DE_COOPERACAO_MUTUA = "Extrato de cooperação mútua"
    EXTRATO_DE_CREDENCIAMENTO = "Extrato de credenciamento"
    EXTRATO_DE_DENUNCIA = "Extrato de denúncia"
    EXTRATO_DE_DEPOSITO = "Extrato de depósito"
    EXTRATO_DE_DISPENSA_DE_CHAMAMENTO_PUBLICO = "Extrato de dispensa de chamamento público"
    EXTRATO_DE_DISPENSA_DE_LICITACAO = "Extrato de dispensa de licitação"
    EXTRATO_DE_DISTRATO = "Extrato de distrato"
    EXTRATO_DE_DOACAO = "Extrato de doação"
    EXTRATO_DE_ESCRITURA_DE_COMPRA_E_VENDA = "Extrato de escritura de compra e venda"
    EXTRATO_DE_EXTINCAO = "Extrato de extinção (lei nº 8.745 - contratação temporária)"
    EXTRATO_DE_FORNECIMENTO = "Extrato de fornecimento"
    EXTRATO_DE_INEXIGIBILIDADE_DE_LICITACAO = "Extrato de inexigibilidade de licitação"
    EXTRATO_DE_INSTRUMENTO_CONVOCATORIO = "Extrato de instrumento convocatório"
    EXTRATO_DE_INSTRUMENTOS_CONTRATUAIS = "Extrato de instrumentos contratuais"
    EXTRATO_DE_MEMORANDO_DE_ENTENDIMENTO = "Extrato de memorando de entendimento"
    EXTRATO_DE_NOTA_DE_EMPENHO = "Extrato de nota de empenho"
    EXTRATO_DE_ORDEM_DE_COMPRA = "Extrato de ordem de compra"
    EXTRATO_DE_ORDEM_DE_EXECUCAO_DE_SERVICO = "Extrato de ordem de execução de serviço"
    EXTRATO_DE_ORDEM_DE_FORNECIMENTO = "Extrato de ordem de fornecimento"
    EXTRATO_DE_PARCERIA = "Extrato de parceria"
    EXTRATO_DE_PARECER_TECNICO = "Extrato de parecer técnico"
    EXTRATO_DE_PERMISSAO_DE_USO = "Extrato de permissão de uso"
    EXTRATO_DE_PERMUTA = "Extrato de permuta"
    EXTRATO_DE_PRORROGACAO_DE_OFICIO = "Extrato de prorrogação de ofício"
    EXTRATO_DE_PROTOCOLO_DE_COOPERACAO = "Extrato de protocolo de cooperação"
    EXTRATO_DE_PROTOCOLO_DE_INTENCAO = "Extrato de protocolo de intenção"
    EXTRATO_DE_RECOLHIMENTO = "Extrato de recolhimento"
    EXTRATO_DE_RECONHECIMENTO = "Extrato de reconhecimento"
    EXTRATO_DE_RECONHECIMENTO_DE_DIVIDA = "Extrato de reconhecimento de dívida"
    EXTRATO_DE_REGISTRO_DE_PRECOS = "Extrato de registro de preços"
    EXTRATO_DE_RERRATIFICACAO = "Extrato de rerratificação"
    EXTRATO_DE_RESCISAO = "Extrato de rescisão"
    EXTRATO_DE_RESCISAO_CONTRATUAL = "Extrato de rescisão contratual"
    EXTRATO_DE_RESILICAO = "Extrato de resilição"
    EXTRATO_DE_SUB_ROGACAO = "Extrato de sub-rogação"
    EXTRATO_DE_TERMO_ADITIVO = "Extrato de termo aditivo"
    EXTRATO_DE_TERMO_DE_AJUSTAMENTO_DE_CONDUTA = "Extrato de termo de ajustamento de conduta"
    EXTRATO_DE_TERMO_DE_COOPERACAO_TECNICA = "Extrato de termo de cooperação técnica"
    EXTRATO_DE_TERMO_DE_ENTREGA = "Extrato de termo de entrega"
    EXTRATO_DE_TERMO_DE_EXECUCAO_DE_PROJETO = "Extrato de termo de execução de projeto"
    EXTRATO_DE_TERMO_DE_EXECUCAO_DESCENTRALIZADA = "Extrato de termo de execução descentralizada"
    EXTRATO_DE_TERMO_DE_FOMENTO = "Extrato de termo de fomento"
    EXTRATO_DE_TERMO_DE_OCUPACAO_DE_IMOVEL = "Extrato de termo de ocupação de imóvel"
    EXTRATO_DE_TERMO_DE_PARCERIA = "Extrato de termo de parceria"
    EXTRATO_DE_TRANSFERENCIA_DE_POSSE = "Extrato de transferência de posse"
    EXTRATO_PREVIO = "Extrato prévio"
    FATO_RELEVANTE = "Fato relevante"
    INSTRUCAO = "Instrução"
    INSTRUCAO_NORMATIVA = "Instrução normativa"
    INSTRUCAO_NORMATIVA_CONJUNTA = "Instrução normativa conjunta"
    LEI = "Lei"
    LEI_COMPLEMENTAR = "Lei complementar"
    LISTA_DE_ANTIGUIDADE = "Lista de antiguidade"
    MEDIDA_PROVISORIA = "Medida provisória"
    MEMORANDO_DE_ENTENDIMENTO = "Memorando de entendimento"
    MENSAGEM = "Mensagem"
    NORMA_COMPLEMENTAR = "Norma complementar"
    OFICIO_CIRCULAR = "Ofício circular"
    ORDEM_DE_SERVICO = "Ordem de serviço"
    ORIENTACAO_NORMATIVA = "Orientação normativa"
    PACTO = "Pacto"
    PARECER_NORMATIVO = "Parecer normativo"
    PAUTA = "Pauta"
    PORTARIA = "Portaria"
    PORTARIA_CONJUNTA = "Portaria conjunta"
    PORTARIA_INTERGOVERNAMENTAL = "Portaria intergovernamental"
    PORTARIA_INTERMINISTERIAL = "Portaria interministerial"
    PROCESSO_DISCIPLINAR = "Processo disciplinar"
    PROPOSTA_ORCAMENTARIA = "Proposta orçamentária"
    PROTOCOLO = "Protocolo"
    PROTOCOLO_DE_INTENCOES = "Protocolo de intenções"
    PROVIMENTO = "Provimento"
    RATIFICACAO = "Ratificação"
    RECOMENDACAO = "Recomendação"
    RECURSO_DISCIPLINAR = "Recurso disciplinar"
    RELATORIOS = "Relatórios"
    REPUBLICACAO = "Republicação"
    RESOLUCAO = "Resolução"
    RESOLUCAO_DO_SENADO_FEDERAL = "Resolução do senado federal"
    RESULTADO_DE_ANALISE = "Resultado de análise"
    RESULTADO_DE_AVALIACAO_TECNICA = "Resultado de avaliação técnica"
    RESULTADO_DE_CADASTRAMENTO = "Resultado de cadastramento"
    RESULTADO_DE_CONCURSO_PUBLICO = "Resultado de concurso público"
    RESULTADO_DE_ELEICAO = "Resultado de eleição"
    RESULTADO_DE_HABILITACAO = "Resultado de habilitação"
    RESULTADO_DE_INDICE_TECNICO = "Resultado de índice técnico"
    RESULTADO_DE_JULGAMENTO = "Resultado de julgamento"
    RESULTADO_DE_JULGAMENTO_DE_LICITACAO = "Resultado de julgamento de licitação"
    RESULTADO_DE_LEILAO = "Resultado de leilão"
    RESULTADO_DE_PROPOSTA_TECNICA = "Resultado de proposta técnica"
    RESULTADO_DE_QUALIFICACAO = "Resultado de qualificação"
    RETIFICACAO = "Retificação"
    RETIFICACAO_DE_EDITAL = "Retificação (de edital)"
    SOLUCAO_DE_CONSULTA = "Solução de consulta"
    SUMULA = "Súmula"
    SUMULA_ADMINISTRATIVA = "Súmula administrativa"
    TERMO_DE_AUTORIZACAO = "Termo de autorização"
    TERMO_DE_LIBERACAO_DE_OPERACAO = "Termo de liberação de operação"


def calculate_from_datetime(publish_to_date: datetime, search_date: SearchDate):
    """
    Calculate parameter `publishFrom` to be passed to the API based
    on publishTo parameter and `search_date`. Perform especial
    calculation to the MES (month) parameter option
    """

    if search_date == SearchDate.DIA:
        return publish_to_date

    elif search_date == SearchDate.SEMANA:
        return publish_to_date - timedelta(days=6)

    elif search_date == SearchDate.MES:
        end_prev_month = publish_to_date.replace(day=1) - timedelta(days=1)
        publish_from_date = end_prev_month.replace(day=publish_to_date.day)
        return publish_from_date - timedelta(days=1)

    elif search_date == SearchDate.ANO:
        return publish_to_date - timedelta(days=364)