FROM node:22-alpine

WORKDIR /app/chatbot/frontend

COPY chatbot/frontend/package.json /app/chatbot/frontend/package.json
RUN npm install

COPY chatbot/frontend /app/chatbot/frontend

EXPOSE 5174
CMD ["npm", "run", "dev"]

