apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
spec:
  template:
    spec:
      containers:
        - name: airflow-db-init
          image: ghcr.io/gestaogovbr/ro-dou:latest
          imagePullPolicy: Always
          command: ["airflow", "db", "migrate"]
          envFrom:
            - secretRef:
                name: airflow-secrets
            - configMapRef:
                name: airflow-config
      restartPolicy: Never
  backoffLimit: 0
