apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    app: airflow
data:
  AIRFLOW__API__BASE_URL: "http://localhost:8080"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: "America/Sao_Paulo"
  AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__TEST_CONNECTION: "enabled"
  AIRFLOW__CORE__AUTH_MANAGER: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
  AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-api-server:8080/execution/"
  AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: "true"
  AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_FAILURE: "false"
  AIRFLOW__EMAIL__DEFAULT_EMAIL_ON_RETRY: "false"
  AIRFLOW__SMTP__SMTP_HOST: "smtp4dev"
  AIRFLOW__SMTP__SMTP_MAIL_FROM: "rodou@gestao.gov.br"
  AIRFLOW__SMTP__SMTP_PORT: "25"
  AIRFLOW__SMTP__SMTP_STARTTLS: "false"
  AIRFLOW_CONN_EXAMPLE_DATABASE_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
  RO_DOU__DAG_CONF_DIR: "/opt/airflow/dags/ro_dou/dag_confs"
  RO_DOU_INLABS_USE_OPENSEARCH: "false"
  OPENSEARCH_HOST: "http://opensearch:9200"
