apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
spec:
  template:
    spec:
      containers:
        - name: airflow-db-init
          image: ghcr.io/gestaogovbr/airflow2-rodou:latest
          command: ["airflow", "db", "init"]
          envFrom:
            - configMapRef:
                name: airflow-config
      restartPolicy: Never
  backoffLimit: 0