apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
stringData:
  AIRFLOW__CORE__FERNET_KEY: "Uqv6pwYWJn7xifR3QAkifMTkupos8mkxaQL2Q7Ydsqw="
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
  AIRFLOW__API__SECRET_KEY: "super-secret-airflow-key-2026"
  AIRFLOW__API_AUTH__JWT_SECRET: "super-jwt-secret-2026"
  # AIRFLOW__SMTP__SMTP_USER:
  # AIRFLOW__SMTP__SMTP_PASSWORD:
  AIRFLOW_CONN_INLABS_DB: "postgresql://airflow:airflow@postgres:5432/inlabs"
  INLABS_PORTAL_LOGIN: "login"
  INLABS_PORTAL_PASSWORD: "password"
  _AIRFLOW_WWW_USER_USERNAME: "airflow"
  _AIRFLOW_WWW_USER_PASSWORD: "airflow"
  OPENSEARCH_USER: "OPENSEARCH_USER"
  OPENSEARCH_PASS: "OPENSEARCH_PASS"
