apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dag-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-dag-processor
  template:
    metadata:
      labels:
        app: airflow-dag-processor
    spec:
      containers:
        - name: airflow-dag-processor
          image: ghcr.io/gestaogovbr/ro-dou:latest
          imagePullPolicy: Always
          command: ["airflow", "dag-processor"]
          envFrom:
            - secretRef:
                name: airflow-secrets
            - configMapRef:
                name: airflow-config
          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs
      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-rodou-logs-pvc
